[package]
name = "agent-ui"
version = "0.1.0"
edition = "2021"

[lib]
name = "agent_ui"
path = "src/lib.rs"

[dependencies]
# GPUI framework
gpui = { git = "https://github.com/zed-industries/zed.git" }

# Async runtime
tokio = { version = "1", features = ["full"] }

# Error handling
anyhow = "1"
